### PR TITLE
Add missing methods as need for integrating the latest version of this crate

### LINKED ISSUE #87: Fq additional methods without arkworks
In working on [#3675](https://github.com/penumbra-zone/penumbra/issues/3675) - making `poseidon377` work in a `no_std` environment without a global allocator, i.e. without arkworks - there is some additional functionality needed in this crate on `Fq` when the `arkworks` feature is _not_ enabled. This ticket is to track those items as we find them:

- [ ] `Fq::pow()` - used in `poseidon-parameters` for the computation of the cofactor matrix [here](https://github.com/penumbra-zone/poseidon377/blob/main/poseidon-parameters/src/matrix.rs#L250) as well as for the computation of the `SubWords` layer in `poseidon-permutation` [here](https://github.com/penumbra-zone/poseidon377/blob/main/poseidon-permutation/src/permutation.rs#L194). This was previously provided via arkwork's `ark_ff::Field` trait ([ref](https://docs.rs/ark-ff/latest/ark_ff/fields/trait.Field.html#method.pow)). 
- [ ] TK

### PR DESCRIPTION
**Pull request by cronokirby**
Don't merge yet, but this serves as a convenient staging point for these changes.

Will eventually close #87.

### CODE REVIEW

**Comment by TalDerei** [comment]
can we merge this?

**Comment by redshiftzero** [comment]
One item still needed to close #87 for https://github.com/penumbra-zone/poseidon377/pull/53 is the `Fq::pow` method, it can be done in a subsequent PR though

**Comment by TalDerei** [comment]
> One item still needed to close #87 for [penumbra-zone/poseidon377#53](https://github.com/penumbra-zone/poseidon377/pull/53) is the `Fq::pow` method

Why do we need `Fq::pow` since [pow](https://docs.rs/ark-ff/latest/ark_ff/fields/trait.Field.html#method.pow) is a provided method? We already have access to Fq::pow().

**Review by redshiftzero — APPROVED** [review]
Let's do Fq::pow in a followup and merge these

**Pull request merged**
